EmployeeApp/Controllers/LeaveController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using EmployeeApp.Data;
using EmployeeApp.Models;
using EmployeeApp.Models.ViewModel;

namespace EmployeeApp.Controllers
{
    public class LeaveController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Leave
        public ActionResult Index()
        {
            return View();
        }

       
        [HttpGet]
        public ActionResult AddLeave()
        {
            return View(new EmployeeLeave());

        }

        [HttpPost]
        public ActionResult Create(EmployeeLeave leave)
        {

            var empId = Session["UserId"] as int?;
            if(empId !=null)
            {
                if(leave.LeaveId==0)
                {

                    var newleave = new EmployeeLeave
                    {
                        EmployeeId = leave.EmployeeId,
                        LeaveType = leave.LeaveType,
                        Reason = leave.Reason,
                        LeaveStartDate = leave.LeaveStartDate,
                        LeaveEndDate = leave.LeaveEndDate,
                        TotalDays = leave.TotalDays,
                        LeaveStatus = "Pending",
                    };

                    db.EmployeesLeave.Add(newleave);
                    db.SaveChanges();

                    TempData["Success"] = "Employee Leave saved successfully!";
                    return RedirectToAction("Index");
                }
                else
                {
                    var existingleave = db.EmployeesLeave.Find(leave.LeaveId);
                    if (existingleave != null)
                    {
                        existingleave.EmployeeId = leave.EmployeeId;
                        existingleave.LeaveType = leave.LeaveType;
                        existingleave.Reason = leave.Reason;
                        existingleave.LeaveStartDate = leave.LeaveStartDate;
                        existingleave.LeaveEndDate = leave.LeaveEndDate;
                        existingleave.TotalDays = leave.TotalDays;
                        db.Entry(existingleave).State = EntityState.Modified;
                    }

                }
                db.SaveChanges();
                TempData["Success"] = "Employee Leave Update successfully!";
                return RedirectToAction("Index");
            }

            return View();
        }




        [HttpGet]
        public ActionResult GetAll()
        {

            if (Session["UserId"] != null && Session["UserRole"] != null)
            {
                int empId = Convert.ToInt32(Session["UserId"]);
                string role = Session["UserRole"].ToString();

                var dataList = db.EmployeesLeave
                 .Where(leave =>
                     (role == "Admin") ||
                     (leave.EmployeeId == empId && leave.LeaveStatus == "Pending")
                 )
                 .Join(db.Employees, 
                     leave => leave.EmployeeId, 
                     emp => emp.EmployeeId, 
                     (leave, emp) => new
                     {
                         leaveId = leave.LeaveId,
                         employeeId = leave.EmployeeId,
                         employeeName = emp.EmployeeName, 
                         leaveType = leave.LeaveType,
                         reason = leave.Reason,
                         leaveStartDate = leave.LeaveStartDate,
                         leaveEndDate = leave.LeaveEndDate,
                         totalDays = leave.TotalDays,
                         leaveStatus = leave.LeaveStatus,
                         role = role
                     })
                     .ToList();


                return Json(new { data = dataList }, JsonRequestBehavior.AllowGet);

            }

            return RedirectToAction("Index", "Account");
        }


        [HttpPost]
        public ActionResult Delete(int id)
        {
            var leave = db.EmployeesLeave.Find(id);
            if (leave != null)
            {
                leave.LeaveStatus = "Cancel";
                db.Entry(leave).State = EntityState.Modified;
            }
        db.SaveChanges();
         return Json(new { success = true });

        }

        //Approved
        [HttpPost]
        public ActionResult Approved(int id)
        {
            var leave = db.EmployeesLeave.Find(id);
            if (leave != null)
            {
                leave.LeaveStatus = "Approved";
                db.Entry(leave).State = EntityState.Modified;
            }
            db.SaveChanges();
            return Json(new { success = true });

        }


        //display dashboard pending leave count
        [HttpGet]
        public JsonResult GetPendingCount()
        {
            int pendingLeaveCount = db.EmployeesLeave.Count(l => l.LeaveStatus == "Pending");
            return Json(pendingLeaveCount, JsonRequestBehavior.AllowGet);

        }

    }
}

EmployeeApp/Controllers/ReviewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EmployeeApp.Data;
using EmployeeApp.Models;
using EmployeeApp.Models.ViewModel;
using WebGrease.Css.Extensions;

namespace EmployeeApp.Controllers
{
    public class ReviewController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Review
        public ActionResult Index()
        {
            var ratingsList = (from r in db.ratings
                               join e in db.Employees 
                               on r.EmployeeId equals e.EmployeeId
                               join department in db.Departments
                               on r.DepartmentId equals department.DepartmentId
                               join designation in db.Designations
                               on r.DesignationId equals designation.DesignationId
                               select new VMRating
                               {
                                   EmployeeId = r.EmployeeId,
                                   EmployeeName = e.EmployeeName, 
                                   Review = r.Review,
                                   Ratings = r.Ratings,
                                   DepartmentName=department.DepartmentName,
                                   DesignationName=designation.DesignationName
                               }).ToList();

            return View(ratingsList); 
        }
        public ActionResult AddReview()
        {
            if (!int.TryParse(Session["UserId"]?.ToString(), out int empId))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Invalid User ID");
            }

            var alreadyExist = db.ratings.FirstOrDefault(r => r.EmployeeId == empId);
            if (alreadyExist != null)
            {
                TempData["ErrorMessage"] = "You have already submitted a review.";
                ViewBag.HideForm = true; // Flag to hide form
                return View(); // Still render the view
            }

            var dataList = (from employee in db.Employees
                            join department in db.Departments on employee.DepartmentId equals department.DepartmentId
                            join designation in db.Designations on employee.DesignationId equals designation.DesignationId
                            where employee.EmployeeId == empId
                            select new VMRating
                            {
                                EmployeeId = employee.EmployeeId,
                                EmployeeName = employee.EmployeeName,
                                DepartmentId = department.DepartmentId,
                                DepartmentName = department.DepartmentName,
                                DesignationId = designation.DesignationId,
                                DesignationName = designation.DesignationName
                            }).FirstOrDefault();

            if (dataList == null)
            {
                return HttpNotFound();
            }

            ViewBag.EmployeeId = dataList.EmployeeId;
            ViewBag.EmployeeName = dataList.EmployeeName;
            ViewBag.DepartmentId = dataList.DepartmentId;
            ViewBag.DepartmentName = dataList.DepartmentName;
            ViewBag.DesigantionId = dataList.DesignationId;
            ViewBag.Designation = dataList.EmployeeName;

            ViewBag.HideForm = false; // Allow form to show
            return View(dataList);
        }

        //Add review page 
        //public ActionResult AddReview()
        //{
        //    int empId = Convert.ToInt32(Session["UserId"]);
        //    var aleadyExist = db.ratings.Where(r => r.EmployeeId == empId).FirstOrDefault();
        //    if(aleadyExist != null)
        //    {


        //        TempData["ErrorMessage"] = "You have already submitted a review.";
        //        return new HttpStatusCodeResult(500);
        //        //return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Already Added the review.");
        //    }


        //    if (!int.TryParse(Session["UserId"]?.ToString(), out empId))
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "Invalid User ID");
        //    }

        //    var dataList = (from employee in db.Employees
        //                    join department in db.Departments
        //                    on employee.DepartmentId equals department.DepartmentId
        //                    join designation in db.Designations
        //                    on employee.DesignationId equals designation.DesignationId
        //                    where employee.EmployeeId == empId
        //                    select new VMRating
        //                    {
        //                        EmployeeId = employee.EmployeeId,
        //                        EmployeeName = employee.EmployeeName,
        //                        DepartmentId = department.DepartmentId,
        //                        DepartmentName = department.DepartmentName,
        //                        DesignationId = designation.DesignationId,
        //                        DesignationName = designation.DesignationName
        //                    }).FirstOrDefault();


        //    if (dataList == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    //assign value viewbag 
        //    ViewBag.EmployeeId = dataList.EmployeeId;
        //    ViewBag.EmployeeName = dataList.EmployeeName;
        //    ViewBag.DepartmentId = dataList.DepartmentId;
        //    ViewBag.DepartmentName = dataList.DepartmentName;
        //    ViewBag.DesigantionId = dataList.DesignationId;
        //    ViewBag.Designation = dataList.EmployeeName;

        //    return View(dataList);
        //}


        [HttpPost]
        public  ActionResult Create(VMRating vMRating)
        {
            var newrating = new Rating
            {
                EmployeeId = vMRating.EmployeeId,
                DepartmentId = vMRating.DepartmentId,
                DesignationId = vMRating.DesignationId,
                Review = vMRating.Review,
                Ratings=vMRating.Ratings,
                CreatedAt=DateTime.Now,
                Createdby="1"
            };

            db.ratings.Add(newrating);
            db.SaveChanges();

            TempData["Success"] = "Rating saved successfully!";
            //return new HttpStatusCodeResult(200);
            return RedirectToAction("Dashboard", "Employee");
        }
    }
}

EmployeeApp/Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" integrity="sha512-..." crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link href="~/Content/css/login.css" rel="stylesheet" />

</head>

<body>

    <div class="container-fluid body-content" style="background-color: #f2e7e7;margin-top:0px;">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")


    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="~/Scripts/js/login.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/Scripts/js/toastr.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

EmployeeApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" integrity="sha512-..." crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="~/Content/css/layout.css" rel="stylesheet" />
</head>
<body>

    @*Navbar*@
    <nav class="custom-navbar">
        <div class="nav-container">
            <div class="nav-brand"><img src="/Images/freashlogo.png" alt="Alternate Text" class="img-fluid" style="width:80px;height:62px;"/></div>
            <div class="nav-profile">

                <div class="profile-dropdown">
                    @*<p>@Session["UserName"]</p>
                        <img src="/Images/profile/@Session["UserProfileImage"]" alt="Profile" class="profile-img" id="profileToggle" />*@
                    <div class="d-flex align-items-center gap-3">
                        <p class="mb-0">@Session["UserName"]</p>
                        <img src="/Images/profile/@Session["UserProfileImage"]" alt="Profile" class="profile-img" id="profileToggle" />
                    </div>

                    <ul class="dropdown-menu pt-2 px-2" id="profileMenu">
                        @*<li class="mx-2 mb-2"><i class="fa fa-user"></i> @Session["UserName"]</li>*@
                        <li class="mx-2"><i class="fas fa-envelope"></i> @Session["UserEmail"]</li>
                        <li><a href="@Url.Action("Logout", "Account")"><i class="fas fa-sign-out-alt"></i> Logout</a></li>

                    </ul>
                </div>
            </div>
        </div>
    </nav>


    @*Sidebar*@
    <div id="sidebar" class="open" style="padding-top:45px;">
        <ul>


            @if (Session["UserRole"] != null && Session["UserRole"].ToString() == "Admin")
            {
                <li><a href="@Url.Action("Dashboard", "Admin")"> Dashboard </a></li>
                <li><a href="@Url.Action("Index", "Department")"> Manage Department </a></li>
                <li><a href="@Url.Action("Index", "Designation")"> Manage Designation  </a></li>
                <li><a href="@Url.Action("Index", "Employee")"> Manage Employees </a></li>
                <li><a href="@Url.Action("Index", "Leave")"> Manage Leave </a></li>
                <li><a href="@Url.Action("Index", "Review")"> Manage Review </a></li>

            }
            else if (Session["UserRole"] != null && Session["UserRole"].ToString() == "Employee")
            {

                <li><a href="@Url.Action("Dashboard", "Employee")"> Dashboard </a></li>
                <li><a href="@Url.Action("Profile", "Employee")">My Profile</a></li>
                <li><a href="@Url.Action("Index", "Leave")"> Leave </a></li>
                <li><a href="@Url.Action("AddReview", "Review")"> Review </a></li>
            }
        </ul>
    </div>

    <div class="container">
        @RenderBody()
    </div>

  
    <div style="position:fixed;bottom:0;left:0;width:100%;background-color:black;color:white;padding-top:10px;">


        <footer>
            <p class="foot">&copy; @DateTime.Now.Year - Employee Salary Slip Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.min.js"></script>

    <script>
        $(document).ready(function () {
            //profile Image
            $("#profileToggle").click(function (e) {
                e.stopPropagation(); // Prevent click from bubbling
                $("#profileMenu").toggle();
            });

            $(document).click(function () {
                $("#profileMenu").hide(); // Hide menu if clicked outside
            });

            $(".dropdown-menu").click(function (e) {
                e.stopPropagation(); // Keep menu open when clicking inside
            });



        });
    </script>


    <script src="//cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js" asp-append-version="true"></script>

    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.3.6/css/buttons.dataTables.min.css" />
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/2.3.6/js/buttons.html5.min.js"></script>

    <!-- JSZip for Excel export -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>

    <!-- pdfmake for PDF export -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.7/vfs_fonts.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/Scripts/js/toastr.js" asp-append-version="true"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

EmployeeApp/Views/Shared/_Notification.cshtml
<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script src="~/Scripts/js/toastr.js" asp-append-version="true"></script>


@if (TempData["Success"] != null)
{

    <script type="text/javascript">
        toastr.success('@TempData["Success"]');
    </script>
}
@if (TempData["Error"] != null)
{

    <script type="text/javascript">
        toastr.error('@TempData["Error"]');
    </script>
}
@if (TempData["Info"] != null)
{

    <script type="text/javascript">
        toastr.error('@TempData["Info"]');
    </script>
}